export const ADD_COUNTER = "add_counter"
export const ADD_TO_CART = "add_to_cart"
export const ADD_CART_ITEM = "add_cart_item"
export const SUB_CART_ITEM = "sub_cart_item"
export const ADD_USER = "add_user"
export const REMOVE_USER = "remove_user"